### ISSUE TITLE
Will this merge into retrofit repo after rxjava2 release stable version?

### ISSUE THREAD

**Issue by gengjiawen** [JakeWharton/retrofit2-rxjava2-adapter#10]
RT

**Comment by vanniktech** [comment]
![screen shot 2016-09-06 at 14 12 09](https://cloud.githubusercontent.com/assets/5759366/18273098/ebc90f08-743b-11e6-8d12-82b990fbcaa9.png)

**Comment by Zhuinden** [comment]
Is that planning to happen?

RxJava2 claims to be a stable release since 3 months ago

**Comment by JakeWharton** [comment]
It already happened

**Comment by Zhuinden** [comment]
@JakeWharton ah, makes sense, but I've tried adding

    compile 'com.squareup.retrofit2:adapter-rxjava2:2.1.0'

And it doesn't seem to exist.

**Comment by JakeWharton** [comment]
Ah, sorry. Only 2.2.0-SNAPSHOT exists. It will be available as stable API
in 2.2.0 in the next two(ish) weeks.

**Comment by Zhuinden** [comment]
I see, thanks!
