### ISSUE TITLE
(Feature Request) CallObservable as public final class

### ISSUE THREAD

**Issue by tunjid** [JakeWharton/retrofit2-rxjava2-adapter#16]
Is it possible to have the CallObservable as a public final class?

I ask because I have a custom RxJavaCallAdapter factory that is lenient in handling OkHttp responses that are not successful by attempting to deserialize the errorBody of the response as a Json of the requested body type. This is because the api I'm working with returns a standard Json error response for all calls to it, so all my POJO objects have an "Error" field for accommodating this error should it occur.

This is important because throwing a HttpException if a response is unsuccessful is fatal for me as it breaks the rx chain, and in situations where I've created a ConnectableObservable with multiple observers, there's a race condition on which observer first consumes the one shot error response body, and the rest throw IllegalArgumentExceptions because the content stream has been read. By being lenient and deserializing the ErrorBody as the the Json it rightfully is, all observers see the same Object forwarded to onNext and I can can deal with my error there.

Currently, I'm having to duplicate the CallObservable class to do this. Is it possible to have the class public instead of package local? I don't mind it being final as I just use an ObservableTransformer on it. The Transformer looks like:

````java
final class LenientResponseTransformer<T>
        implements
        Function<Response<T>, Observable<T>>,
        ObservableTransformer<Response<T>, T> {

    HttpCodeAppender codeAppender;
    Converter<ResponseBody, T> converter;

    public LenientResponseTransformer(Converter<ResponseBody, T> converter,
                                      @Nullable HttpCodeAppender codeAppender) {
        this.converter = converter;
        this.codeAppender = codeAppender;
    }

    @Override
    public Observable<T> apply(Response<T> response) {
        T resultBody;

        if (response.isSuccessful()) {
            resultBody = response.body();
        }
        else {
            try {
                resultBody = converter.convert(response.errorBody());

                if (codeAppender != null) {
                    resultBody = codeAppender.appendHttpCode(response.code(), resultBody);
                }
            }
            catch (Exception e) {
                // Forward this exception down the chain. The errorBody could not be deserialized
                // into the expected type.
                throw new RuntimeException(new HttpException(response));
            }
        }
        return Observable.just(resultBody);
    }

    @Override
    public ObservableSource<T> apply(Observable<Response<T>> observable) {
        return observable.flatMap(this);
    }
}
````

**Comment by vanniktech** [comment]
I'm also interested in having a way to hook up and transform the returned Observable Type by making of the errorBody.

Do you have plans on opening up the API?

**Comment by JakeWharton** [comment]
No plans. These types are implementation details.

You can write your own `CallAdapter.Factory` and use delegation to accomplish this. There's an example here: https://speakerdeck.com/jakewharton/making-retrofit-work-for-you-droidcon-uk-2016?slide=205. The full code for that will be in Retrofit's `samples/` folder in the coming weeks.

**Comment by tunjid** [comment]
@JakeWharton I did create my own `CallAdapter.Factory`, and it delegates to the RxJava2CallAdapterFactory when the the parametrized type is Result or Response. 

The issue is I have to make an exact copy of the `CallObservable` class which wouldn't be necessary if that class was public.

**Comment by JakeWharton** [comment]
These types are moving into Retrofit soon and I definitely don't want to
expose them there. Maintaining the flexibility of the implementation
details of these call adapters is very important to me. If you look at the
evolution of the RxJava 1 call adapter it has changed dramatically and if
any of its types were public we would not have been able to do that.

Your best bet is instead to copy the class and modify it, rather than
delegating to it. If you know exactly the behavior you want then I think
it's perfectly appropriate to supply your own call adapter.

**Comment by vanniktech** [comment]
On the slide 205 it should be

```java
retrofit.callAdapter(returnType, annotations);
```

instead of 

```java
retrofit.nextCallAdapter(returnType, annotations);
```

as the latter does not exist.

**Comment by JakeWharton** [comment]
Nope. nextCallAdapter is the correct method.

**Comment by vanniktech** [comment]
But then there's a [parameter missing](https://github.com/square/retrofit/blob/32ace0894882a98f56cd509fee1bcc7dff804347/retrofit/src/main/java/retrofit2/Retrofit.java#L213) in the slide.

**Comment by JakeWharton** [comment]
Yeah there's errors all over. No big deal.
