### ISSUE TITLE
Feature Request:  RetrofitExceptions in RxJava2

### ISSUE THREAD

**Issue by Moudi2020** [JakeWharton/retrofit2-rxjava2-adapter#19]
[Feature Request] modify RxJava2CallAdapterFactory to handle different RetrofitExceptions similar to RxErrorHandlingCallAdapterFactory used in RxJava 1.

Here : https://gist.github.com/koesie10/bc6c62520401cc7c858f#file-retrofitexception-java
http://bytes.babbel.com/en/articles/2016-03-16-retrofit2-rxjava-error-handling.html

**Comment by JakeWharton** [comment]
RetrofitError was the single biggest design mistake of Retrofit 1 and it
will never be coming back. Currently both the RxJava 1 and 2 adapters
behave the same with IOException and HttpException indicating network or
HTTP errors and anything else being a configuration problem. No plans to
change this.

**Comment by Moudi2020** [comment]
Thanks for prompt reply Jacke. Currently am getting the throwable of GaiException instead of IOException. I have posted this on StackOverflow as well. 
http://stackoverflow.com/questions/41379815/handling-network-error-in-rxjava-2-retrofit-2
