### ISSUE TITLE
Explanation for Flowable vs Observable?

### ISSUE THREAD

**Issue by ngoctranfire** [JakeWharton/retrofit2-rxjava2-adapter#20]
Hi There, So I was using this to create a retrofit service and I ran into this problem. I noticed that when I am using the RxJava2CallAdapter, it doesn't seem to support Flowable<Model>. For example, I tried the following: 
```
@GET("/services/rest/?method=flickr.photos.getRecent")
    Flowable<PhotoSearchResult> getRecentPhotos(@Nullable @Query("extras") String extras,
                                            @Query("per_page") int perPage,
                                            @Query("page") int page);
```
That never actually triggers my onNext(), onCompleted(), etc...
Maybe I'm missing something, but ideally for a network call, I read up on RxJava2, it advises us to use something like Flowable. However, when I try Flowable, it never triggers the onNext() call in my .subscribe() function.
It will work correctly if I instead make my Service interface return an Observable<Model>. Can someone help explain this to me. I feel as if I'm totally missing something here...

**Comment by JakeWharton** [comment]
There are tests for `Flowable` which show that it behaves the same way as `Observable`: https://github.com/JakeWharton/retrofit2-rxjava2-adapter/blob/master/src/test/java/com/jakewharton/retrofit2/adapter/rxjava2/FlowableTest.java. Can you express your difficulties in the form of a failing test?

**Comment by ngoctranfire** [comment]
So I tried the following:
```
@GET("/services/rest/?method=flickr.photos.getRecent")
    Maybe<PhotoSearchResult> getRecentPhotos(@Nullable @Query("extras") String extras,
                                            @Query("per_page") int perPage,
                                            @Query("page") int page);```
and then I did this and it seems to be working just fine:

```
@Override
    public void getRecentPhotos(final @Nullable String extras, final int itemsPerPage,
                                final int pageNumber,
                                final @NonNull FetchImageListener fetchListener) {
        flickrService.getRecentPhotos(extras, itemsPerPage, pageNumber)
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .cache()
            .subscribe(new MaybeObserver<PhotoSearchResult>() {
                @Override
                public void onSubscribe(Disposable s) {
                    Timber.i("Started flickr.photos.recent, with extras=%s, itemsPerPage=%d, pageNumber=%d", extras, itemsPerPage, pageNumber);
                }

                @Override
                public void onSuccess(PhotoSearchResult photoResults) {
                    fetchListener.onImagesFetchSuccess(photoResults.photoResults.photos);
                }

                @Override
                public void onError(Throwable t) {
                    Timber.e(t);
                    fetchListener.onImagesFetchError(t.getMessage());
                }

                @Override
                public void onComplete() {
                    Timber.i("Finished flickr.photos.recent, with extras=%s, itemsPerPage=%d, pageNumber=%d", extras, itemsPerPage, pageNumber);
                }
            });
    }```.

However, if I convert the above to the following:
```
@GET("/services/rest/?method=flickr.photos.getRecent")
    Flowable<PhotoSearchResult> getRecentPhotos(@Nullable @Query("extras") String extras,
                                            @Query("per_page") int perPage,
                                            @Query("page") int page);
```
, and my flowable handling to the following: 
```
flickrService.getRecentPhotos(extras, itemsPerPage, pageNumber)
            .subscribeOn(Schedulers.io())
            .observeOn(AndroidSchedulers.mainThread())
            .subscribe(new Subscriber<PhotoSearchResult>() {
                @Override
                public void onSubscribe(Subscription s) {
                    Timber.i("Started flickr.photos.recent, with extras=%s, itemsPerPage=%d, pageNumber=%d", extras, itemsPerPage, pageNumber);
                }

                @Override
                public void onNext(PhotoSearchResult photoResults) {
                    Timber.i("Next data flickr.photos.recent, with extras=%s, itemsPerPage=%d, pageNumber=%d", extras, itemsPerPage, pageNumber);
                    fetchListener.onImagesFetchSuccess(photoResults.photoResults.photos);
                }

                @Override
                public void onError(Throwable t) {
                    Timber.e(t);
                    fetchListener.onImagesFetchError(t.getMessage());
                }

                @Override
                public void onComplete() {
                    Timber.i("Finished flickr.photos.recent, with extras=%s, itemsPerPage=%d, pageNumber=%d", extras, itemsPerPage, pageNumber);
                }
            });```
I am never able to reach my onNext(), onError(), or onComplete(). However, it enters onSubscribe() as expected.

**Comment by zoomself** [comment]
public void onSubscribe(Subscription s) {
                    //add this
                     s.request(128);
                    Timber.i("Started flickr.photos.recent, with extras=%s, itemsPerPage=%d, pageNumber=%d", extras, itemsPerPage, pageNumber);
                }

**Comment by ngoctranfire** [comment]
@zoomself . That makes sense. I was using the flowable wrong. I believe I needed to add that `s.request`.
